### ISSUE TITLE
Anyword option

### ISSUE THREAD

**Issue by freddez** [dtao/angular-fast-matcher#1]
Please, could you add the "anyword" option, like in fast-matcher-library ?
Thank you very much,
Fred.

**Comment by dtao** [comment]
Yes I can, @freddez! Just for you :)

**Comment by freddez** [comment]
Thanks a lot !!

On Mon, Nov 3, 2014 at 10:51 PM, Dan Tao notifications@github.com wrote:

> Closed #1 https://github.com/dtao/angular-fast-matcher/issues/1 via
> d5b788a
> https://github.com/dtao/angular-fast-matcher/commit/d5b788ac1715366c7dc2707ffe50e941ec9c355d
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dtao/angular-fast-matcher/issues/1#event-187673517.

## 

Frédéric de Zorzi - PimenTech
http://www.pimentech.fr
7bis, rue de LESSEPS - 75020 PARIS
Tel  : +33663180800
